### ISSUE TITLE
Lost data

### ISSUE THREAD

**Issue by FireBlaze134** [exyl-exe/ydis#1]
So my geometry dash randomly uninstalled (not sure why) and ydis basically removed all of the data of the levels that i have played since I downloaded it like 9 days ago. I tried to import existing data, but it says thats only for people who used beta, which I didnt. Its not really a huge deal since it was only 9 days of progress, but i would like to know if this problem is solvable

**Comment by exyl-exe** [comment]
I believe your data loss in unrelated to Geometry Dash being uninstalled, as ydis' data is completely independant from any of the game's files. First thing you can try, if you still have your old data, is to import it. I might have worded it poorly but you can still import data without having used the beta.
Saves are initially stored in Appdata/Roaming/Ydis/records. If there are still files there, you can try to select this folder when using the "import existing data" option. If you have moved your save files before your data loss, the saves should still be at the location you had selected.
In case there aren't any files at these locations, your data is unfortunately probably lost. In this case, I'd appreciate any info that could help me identify the issue (what was the last thing you were doing in Ydis, options you were using etc.)
Let me know if this helped or if you need any clarification. I'm also availaible on discord (Exyl#8354), where I will probably answer faster.
