### ISSUE TITLE
It isn't working

### ISSUE THREAD

**Issue by Buprone** [exyl-exe/ydis#4]
For Some Reason when I download YDIS and I open it, it doesn't give me an app, instead it gives me a windows markup fil
![Screenshot (2)](https://user-images.githubusercontent.com/108161571/175752889-61bf5ba6-d02a-457d-bba4-908203377299.png)
e

**Comment by Buprone** [comment]
Does anyone know how to fix this

**Comment by exyl-exe** [comment]
You've downloaded the source code of the application, not the application. What you are looking for is https://github.com/exyl-exe/ydis/releases/download/v1.1/ydis-setup.exe

**Comment by Buprone** [comment]
Thanks for your help, I appreciate it.
